name: Security check - Bandit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bandit
        run: |
          sudo apt-get update
          sudo apt-get install bandit

      - name: Run Bandit
        run: |
          bandit -r . --format=txt --output=output/security_report.txt

      - name: Upload Bandit report
        uses: actions/upload-artifact@v1
        with:
          name: Security report
          path: output/security_report.txt
