name: SAST with Semgrep

on:
  push:
    branches:
      - master

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          semgrep-version: 'latest'

      - name: Install Semgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y semgrep

      - name: Run Semgrep
        run: semgrep ci --severity=high,medium,low --format=json

      - name: Upload Semgrep findings
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-findings
          path: findings.json

