name: Bandit Scan

on:
  push:
    branches: [master]

jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install jq

      - name: Run Bandit
        id: bandit
        run: |
          bandit -r . -ll -f json -o bandit_report.json || echo "::set-output name=bandit_failed::true"
          pwd

      - name: Parse Bandit Report
        id: parse_report
        if: steps.bandit.outputs.bandit_failed != 'true'
        run: |
          cat bandit_report.json | jq -c '.' > bandit_report_formatted.json || echo "::set-output name=parse_failed::true"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bandit Report
          path: bandit_report_formatted.json
