name: Semgrep Full Scan

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * 6'

jobs:
  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Clone application source code
        uses: actions/checkout@v3

      - name: Full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      - name: Install sarifconv
        run: |
          wget https://github.com/microsoft/sarif-visualizer/releases/latest/download/sarifconv-linux-netcoreapp.zip
          unzip sarifconv-linux-netcoreapp.zip
          chmod +x sarifconv

      - name: Convert SARIF to HTML
        run: |
          ./sarifconv report.sarif

      - name: Save HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: parsed_report
          path: output.html
